version: '3.3'

services:
  rabbitmq:
    image: rabbitmq:3-management
    networks:
      - staging_rabbitmq
    volumes:
      - staging_rabbitmq_data:/var/lib/rabbitmq

volumes:
  staging_rabbitmq_data:
    external: true

networks:
  staging_rabbitmq:
    external: true
