version: '3.3'

services:
  postgres:
    image: postgres:14-alpine
    volumes: 
      - staging_postgres:/var/lib/postgresql/data
    networks:
      - staging_database
    secrets:
      - postgres_staging_password
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_staging_password
      POSTGRES_USER: postgres

secrets:
  postgres_staging_password:
    external: true

volumes:
  staging_postgres:
    external: true

networks:
  staging_database:
    external: true
